name: Release with goreleaser
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: "0"

      - name: Wait for build checks
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          running-workflow-name: "build"

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
