name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every friday, at 13:20 UTC
    - cron: '20 13 * * 5'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
